### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [SofyaKisliak/grid-template_20211701#1]
1)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/115033295-f07d5b00-9ed2-11eb-896f-c27f8e837379.png)

2)
цвет плейсхолдера не соответвует макету
![image](https://user-images.githubusercontent.com/8464662/115033533-35a18d00-9ed3-11eb-86a6-883781acc2ed.png)

3)
некорректное поведение меню - всегда открыто
![image](https://user-images.githubusercontent.com/8464662/115033612-4d791100-9ed3-11eb-9468-e409371cf5f9.png)

**Comment by SofyaKisliak** [comment]
https://github.com/SofyaKisliak/grid-template_20211701
https://sofyakisliak.github.io/grid-template_20211701/


пт, 16 апр. 2021 г. в 16:47, Andrey ***@***.***>:

**Comment by Alecto** [comment]
4)
неправильное отображение формы
![image](https://user-images.githubusercontent.com/8464662/115730645-2917ab80-a38f-11eb-99d0-cf4af24fecb1.png)

**Comment by SofyaKisliak** [comment]
https://github.com/SofyaKisliak/grid-template_20211701
https://sofyakisliak.github.io/grid-template_20211701/

Кинозал
https://github.com/SofyaKisliak/kinozal_template_20210418
https://sofyakisliak.github.io/kinozal_template_20210418/

чт, 22 апр. 2021 г. в 17:22, Andrey ***@***.***>:

**Comment by Alecto** [comment]
да, верно, работа принята

сб, 24 апр. 2021 г. в 15:56, SofyaKisliak ***@***.***>:
